################################################################################
# training parameters
################################################################################
train:
  loss: "focal_gamma"
  max_epochs: 100
  lr: 0.005
  min_lr: 2.0e-5
  wup_epochs: 3
  cos_epochs: 97
  momentum: 0.9
  lr_decay: 0.9
  w_decay: 0.01
  batch_size: 2
  report_batch: 200
  report_epoch: 1
  epsilon_w: 0.01
  workers: 4

################################################################################
# backbone parameters
################################################################################
model:
  name: "SJNetl3"
  in_channels: 8
  dropout: 0.5
  bn_d: 0.01
  use_mps: False

################################################################################
# postproc parameters
################################################################################
post:
  KNN:
    use: True
    params:
      knn: 5
      search: 5
      sigma: 1.0
      cutoff: 1.0

################################################################################
# classification head parameters
################################################################################
dataset:
  labels: "SemanticKitti"
  scans: "SemanticKitti"
  sensor:
    name: "HDL64"
    type: "spherical"
    img_prop:
      width: 512
      height: 512
    img_means:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    img_stds:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
    fov_up: 3
    fov_down: -23
  max_points: 130000
