################################################################################
# training parameters
################################################################################
train:
  # loss: "xentropy"       # must be either xentropy or iou
  loss: "focal_gamma"
  max_epochs: 100
  lr: 0.0002               # sgd learning rate
  min_lr: 1.0e-5
  wup_epochs: 3         # warmup during first XX epochs (can be float)
  cos_epochs: 97
  momentum: 0.9          # sgd momentum
  lr_decay: 0.9        # learning rate decay per epoch after initial cycle (from min lr)
  w_decay: 0.05        # weight decay
  batch_size: 2       # batch size
  report_batch: 200       # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  epsilon_w: 0.1       # class weight w = 1 / (content + epsilon_w)
                         # sample images (one per batch of the last calculated batch)
                         # in log folder
  workers: 4           # number of threads to get data

################################################################################
# backbone parameters
################################################################################
model:
  name: "SJunNet7"  
  in_channels: 6
  dropout: 0.5
  bn_d: 0.01
  use_mps: False

################################################################################
# postproc parameters
################################################################################
post:
  KNN:
    use: True
    params:
      knn: 5
      search: 5
      sigma: 1.0 
      cutoff: 1.0

################################################################################
# classification head parameters
################################################################################
# dataset (to find parser)
dataset:
  labels: "SemanticKitti"
  scans: "SemanticKitti"
  # max_points: 150000 # max of any scan in dataset
  sensor:
    name: "HDL64"
    type: "spherical" # projective
    # fov_up: 3
    # fov_down: -25 
    img_prop:
      # width: 512
      width: 512
      height: 512
    img_means: # max_z, mean_z, max_r, density
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    img_stds: 
      - 1.0
      - 1.0
      - 1.0
      - 1.0

    fov_up: 3
    fov_down: -23
  max_points: 130000 # max of any scan in dataset
